name: cheese
adopt-info: cheese
# Temporary manual setting version number
# https://gitlab.gnome.org/GNOME/cheese/-/merge_requests/60
version: '44.0'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

slots:
  # for GtkApplication registration
  cheese:
    interface: dbus
    bus: session
    name: org.gnome.Cheese

apps:
  cheese:
    extensions: [ gnome ]
    command: usr/bin/cheese
    desktop: usr/share/applications/org.gnome.Cheese.desktop
    plugs:
      - audio-playback
      - camera
      - home
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  cheese:
    source: https://gitlab.gnome.org/GNOME/cheese.git
    source-type: git
    source-tag: '44.0.1'
    source-depth: 1
    parse-info: [usr/share/metainfo/org.gnome.Cheese.appdata.xml]
    override-build: |
      sed -i.bak -e 's|=org.gnome.Cheese$|=${SNAP}/meta/gui/org.gnome.Cheese.svg|g' $CRAFT_PART_SRC/data/org.gnome.Cheese.desktop.in
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/icons/scalable/org.gnome.Cheese.svg $CRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Cheese.desktop $CRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
     - --prefix=/usr
     - --buildtype=release
     - -Dgtk_doc=false
     - -Dman=false
    build-packages:
     - gnome-video-effects-dev
     - libcanberra-gtk3-dev
     - libclutter-gst-3.0-dev
     - libgstreamer-plugins-bad1.0-dev
    stage-packages:
    - gnome-video-effects
    - libclutter-gst-3.0-0

  libraries:
    plugin: nil
    prime:
      - "-*"

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [libraries]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
